title:            "Propeller - A Static Site Generator"
author:           "Propeller"
year:             "2014"
componentsFolder: "app/components"
cssFolder:        "app/css"
jsFolder:         "app/js"
imgFolder:        "app/img"
cssMainFile:      "styles"
jsMainFile:       "scripts"
